# .github/workflows/build-and-push-on-main.yml
name: Build and Push Docker Image on Main

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: general

    steps:
    # 1) Checkout SOLO lectura (sin credenciales de push)
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # 2) Configurar Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3) Login a Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4) Definir la versión a partir del número de run
    - name: Set VERSION env
      run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

    # 5) Build & push con las dos etiquetas
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          maximorero14/k8_auth:latest
          maximorero14/k8_auth:v${{ env.VERSION }}